# IAC Pipeline to Deploy Kubernetes
# Maintainer bradmccoydev@gmail.com

trigger:
- main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactsStagingDirectory)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'bradmccoydev Development (118d61e4-c20f-418b-8773-41bb50833cd9)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: '#az aks get-credentials --resource-group ''dev'' --name ''bradmccoydev'''
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.14.5'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'mkdir ~/.ssh && echo $(SSH_KEY) > ~/.ssh/id_rsa.pub'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(Build.SourcesDirectory)/Terraform'
    backendServiceArm: 'bradmccoydev Development (118d61e4-c20f-418b-8773-41bb50833cd9)'
    backendAzureRmResourceGroupName: 'S365-DEV'
    backendAzureRmStorageAccountName: 'generalpoc'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'bradmccoydev.tfstate'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(Build.SourcesDirectory)/Terraform'
    commandOptions: '-var-file="terraform.tfvars" -var "mongodb_password=$(MONGODB_PASSWORD)" -var "cloudflare_api_token=$(CLOUDFLARE_API_TOKEN)" -var "postgres_password=$(postgres_password)" -lock=false"'
    environmentServiceNameAzureRM: 'bradmccoydev Development (118d61e4-c20f-418b-8773-41bb50833cd9)'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(Build.SourcesDirectory)/Terraform'
    commandOptions: '-var-file="terraform.tfvars" -var "mongodb_password=$(MONGODB_PASSWORD)" -var "cloudflare_api_token=$(CLOUDFLARE_API_TOKEN)" -var "postgres_password=$(postgres_password)"'
    environmentServiceNameAzureRM: 'bradmccoydev Development (118d61e4-c20f-418b-8773-41bb50833cd9)'

