# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: 58445e81-389a-46be-9b20-f98610b37262
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: f7b8d1c4-c52f-4aaf-8c24-860c2b1c9d0c
      ARM_TENANT_ID: 1543c9b8-a1d1-4f26-bffb-1368aaeb582e

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Install Terraform
      run: |-
        ls
        pwd
        if [ ! -f "terraform" ]; then
            curl -SL "https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip" --output terraform.zip
            unzip "terraform.zip"
            sudo mv terraform /usr/local/bin
            rm terraform.zip
        fi
        terraform --version
    
    - name: Terraform Init
      run: |-
        ls
        cd src
        terraform init

    - name: tfsec
      uses: aquasecurity/tfsec-pr-commenter-action@main
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
